feat: add tofuenv
virtualroot/awesome-opentofu pull request #23
Opened 2024-01-04 16:19 UTC by kvendingoldo

2024-01-04 19:52 UTC, virtualroot requested changes

2024-01-04 19:52 UTC, virtualroot commented on README.md
> +- [tofuenv](https://github.com/tofuutils/tofuenv) - OpenTofu version manager inspired by tfenv
```suggestion
- [tofuenv](https://github.com/tofuutils/tofuenv) - OpenTofu version manager inspired by tfenv.
```

As suggested by the [linter](https://github.com/virtualroot/awesome-opentofu/actions/runs/7412050852/job/20174527234?pr=23#step:3:10)

2024-01-04 20:53 UTC, kvendingoldo commented
fixed

2024-01-05 09:16 UTC, virtualroot approved these changes

2024-01-05 09:19 UTC, merged